# Generated by Django 4.0.2 on 2022-02-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_order_paid_order_payment_id_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
