# Generated by Django 4.0.2 on 2022-03-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_leave_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave_Comment',
        ),
    ]
